// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QycDsGrPRqdi3sTqxEmnsRAYASoL35o',
    appId: '1:231088823155:web:e760b5349bfc8c8afcc306',
    messagingSenderId: '231088823155',
    projectId: 'foodlis-1f062',
    authDomain: 'foodlis-1f062.firebaseapp.com',
    storageBucket: 'foodlis-1f062.appspot.com',
    measurementId: 'G-GSKY52MSPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrEZs_NyE9fmh4okV6mzwpjCl8ZB_C1IM',
    appId: '1:231088823155:android:25ed626e518380f6fcc306',
    messagingSenderId: '231088823155',
    projectId: 'foodlis-1f062',
    storageBucket: 'foodlis-1f062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1KbErFu42rKn2jPumaGVaAhguhw4MWCc',
    appId: '1:231088823155:ios:cf6e2d0f2eb1a34bfcc306',
    messagingSenderId: '231088823155',
    projectId: 'foodlis-1f062',
    storageBucket: 'foodlis-1f062.appspot.com',
    iosBundleId: 'com.example.foodLis',
  );

}